<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Provisioning\Module'                        => __DIR__ . '/Module.php',
    'Provisioning\Controller\ProvisioningController' => __DIR__ . '/src/Provisioning/Controller/ProvisioningController.php',
);
