<?php 
   $var = $this->form;
   function swi($char,$var)
{
    if(!$var[$char])
    {
        return $char;
    }
    else
    {
        return $var[$char];
    }
}

?>

<select id="lan" onchange="language1()">
  <option value =""><?php echo swi('language',$var);?></option>
  <option value ="chinese">汉语</option>
  <option value ="english">English</option>
</select>

&nbsp;&nbsp;&nbsp;&nbsp;

<a href="/provisioning/Provisioning/index">Join Now!</a>

<div>

    <form method="post" action="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/login">

    <?php echo swi('username',$var);?> 
    <input name = 'username' type="text">
    </br>
    <?php echo swi('password',$var);?> 
    <input name="password" type="password">
    </br>
    <input type="submit" value="Login" >
        
    </form>
</div>

<script type="text/javascript">
    
    function language1()
    {
        var hostName = window.location.host ;
        var s = $("#lan").val();
        $.ajax({
                type: 'post',
                async: false,
                url: 'http://'+hostName+'/application/Index/test',
                dataType: 'json',
                data: {
                    language:s+'.php'
                }
                   
        });
        window.location.reload();
    }
</script>